rohan9024/ecommerce

package-lock.json, src/components/Home.js, src/components/ScrollUp.js
**Feature**
So basically i added simply button to scroll to top as you requested in https://github.com/rohan9024/ecommerce/issues/1
https://user-images.githubusercontent.com/73834979/205532190-8194de83-5a30-40bd-9f80-e0049d303a42.mov
=> button scroll-to-top

src/App.js, src/pages/ProductDescription.js
Added a responsive product description that takes product id a parameter fixing issue #10 
Go to `http://localhost:3000/product/productId` for viewing the page. (where id can be any id of product of your choice).
=> added responsive product desc. page

src/components/Kids.js, src/components/Men.js, src/components/Shoes.js, src/components/Women.js
Issue - Add margin top and margin bottom #23
Changes - Added margin top and bottom in Men, Women, Kids and Shoes Components
Screenshots for Men Component
- Top Margin
-  Bottom Margin
=> add top and bottom margin

src/App.js, src/Login.js, src/Signup.js, src/components/Navbar.css
Issue #24 . Created the signup page. Attached screenshot below.
=> Added signup page

src/components/Men.js
=> Made men's page responsive

src/components/Women.js
=> Made women's page responsive

src/components/Shoes.js
Made the shoes page responsive
=> Made the shoes page responsive

src/components/Navbar.css
=> reduced bottom shadow

src/components/Fourth.js
Added hover animation in explore section
=> Added hover animation in explore section

src/App.js, src/ScrollToTop.js, src/components/Fourth.js
Added links in the explore categories section. 
For example when user clicks on Men, it should go to Men's page, similarly for women and kids.
=> Added links in the explore section

src/App.js, src/Signup.js, src/components/Profile.js, src/firebase.js
Closes #55 . Improved the design of the profile page. Attached screenshots.
=> Modified the profile page

ENVinstructions.md
=> Updated the env instructions file

src/App.js, src/JsonData/data.js
=> Changes Done

src/components/Navbar.css
hello @rohan9024 i have changed search bar which was close button have removed
=> close button is removed from the search bar

src/components/Contributor_card.js, src/components/Contributor_data.js
Leaderboard of top contributors based on number of commits. It also includes number of line addition and line deletion.
Here is a screenshot of that.
=> [ADDED]: Display leaderboard of github users

src/App.js, src/components/Men.js, src/components/ShoeItem.js
Closes #89 . Fixed search results page. Screenshot attached.
=> Fixed search results page

src/JsonData/data.js, src/components/Admin.js, src/components/Shoes.js
Added more sub-categories in shoes
You closed issue #80 , but it was not resolved
=> Added sub-sections in shoes

src/App.js, src/components/Profile.js, src/components/ProtectedRoute.js
https://user-images.githubusercontent.com/91470808/209369135-a8519e90-4018-47e3-a11b-2e26dfc998fa.mp4
Added a protected route for admin page so that only admins can access it.
Admin should have the email as "admin@gmail.com"
If you want to access the admin page create a user with email as "admin@gmail.com" otherwise you won't be able to access it
Access to the admin page directly from the navigation url is also disabled
Closes #70
=> Configured admin login

src/components/Men.js, src/components/ShoeItem.js, src/components/Sort.js
Closes #94 . Made the men's page responsive. 
Issue: Earlier the sub-category page was not responsive and the headings were not visible in mobile screen. So I fixed the layout.
Screenshot attached.
=> Made the men's page responsive

src/App.js, src/components/Men.js, src/components/ShoeItem.js, src/pages/ProductDescription.js
Added single product description for each item in mens page. Attached video preview:
https://user-images.githubusercontent.com/66685553/209425744-b3e91a1a-4a1c-47c2-aba2-87a40a7f581b.mp4
=> Added single product description for each item in mens page

src/components/Men.js, src/components/Shoes.js
Made shoes page responsive. Screenshots attached.
=> Made shoes page responsive

src/components/Kids.js
Made kids page responsive. Screenshots attached.
=> Made kids page responsive

src/components/Men.js, src/components/Shoes.js
Added single product description for each item in shoes page. Attached video preview:
https://user-images.githubusercontent.com/66685553/209447090-d08d0ef1-001f-4582-860e-3c63bfcdd4af.mp4
=> Added single product description for each item in shoes page

package-lock.json, package.json, src/App.js, src/components/Navbar.css, src/components/Navbar.js, src/components/SmoothScroll.js, src/index.css
Resolves #67 
Added Smooth Scroll Bar and Bounce Effect 
https://user-images.githubusercontent.com/81313711/209472519-13fd2091-d0a0-4a89-a34c-8aa0904b7c15.mp4
=> Scroll  bar

src/components/Kids.js
Added single product description for each item in kids page. Attached video preview:
https://user-images.githubusercontent.com/66685553/209446688-c3e77dce-b68f-45c7-930f-93770ca3ec13.mp4
=> Added single product description for each item in kids page

src/components/Women.js
Added single product description for each item in women's page. Attached video preview:
https://user-images.githubusercontent.com/66685553/209446503-e7a81bb7-eec4-4dc5-a880-ca8c28940503.mp4
=> Added single product description for each item in women's page

src/App.js, src/components/Cart.js, src/components/Men.js, src/components/Navbar.js, src/pages/ProductDescription.js
Closes #3. Added Cart page and add-to-cart functionality. Before viewing cart page, users first have to login. Attached video preview.
https://user-images.githubusercontent.com/66685553/209558966-d4a3a0cb-5f37-4084-b749-58866aa2d0da.mp4
=> Added Cart page and add-to-cart functionality

package-lock.json, package.json, src/App.js, src/components/AdvancedBanner.js, src/components/Home.js, src/components/Parallax.css, src/components/Parallax.js, src/components/SmoothScroll.js
Closes #49 . Added parallax effect on homepage.
=> Added parallax effect on homepage

package-lock.json, package.json, src/App.js, src/Login.js, src/components/Cart.js, src/components/Home.js, src/components/Profile.js, src/components/SmoothScroll.js, src/pages/ProductDescription.js
Closes #110. Three types of alerts:
=> Added Alerts component

src/components/Kids.js, src/components/Men.js, src/components/ShoeItem.js, src/components/Shoes.js, src/components/Women.js
closes #122 
Changed to grid system. Previously the cards were changing sizes based on the text content causing the entire flexbox to malfunction. Images now scale up with the card so it looks good on every screen size.
=> transitioned to grid added responsiveness

src/Signup.js
Add form validation and error handle on Signup page:-
[Screencast from 2023-12-12 23-35-44.webm](https://github.com/rohan9024/ecommerce/assets/106171546/8255f3b2-b767-4e0b-aeca-41849631f430)
=> Add form validation and error handle on Signup page

src/components/Navbar.css, src/components/Navbar.js
Fixes: #132 
Added animations as stated.
=> Added animations for navitems

src/404-page.js, src/App.js
Closes #171 
added a 404 page which occurs when a redirect url problem occurs
=> added a 404 page #171

src/components/CardBanner.js
issue #176 
added autoplay with a duration of 3 seconds.
=> Added autoplay for cardBanners

src/components/Cart.js
issue #180 
added the same delete icon as used in wishlist, also replaced the hardcoded data with dynamic data for number of items,
maintained responsivness
=> integrated delete item functionality in cart
